// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogrfonizewtajbzgmbyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ncmZvbml6ZXd0YWpiemdtYnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDMwODgsImV4cCI6MjA2MzgxOTA4OH0.oGb2OfYYuD5q4cn31U7EhEpampFffO0KQKuGa0zbx7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);